"server":
  "con_type": "tcp"
  "port": "8080"

"db":
  "host": "localhost"
  "port": "5432"
  "username": "amir"
  "db_name": "library"
  "ssl_mode": "disable"

"token":
  "access_token_ttl": "1m"
  "refresh_token_ttl": "131400m"

"redis":
  "address": "localhost:6379"
  "token_db": "0"
